#!/bin/bash

sudo apt-get update 

sudo apt-get upgrade -y

sudo apt-get install neofetch -y

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz

tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz

cd SRBMiner-Multi-2-4-7 || exit

declare -A running_list=(
    [DOGE]=DQPFq8Zzp89HAXxeM6LY1ya4hsy2vV5BSY
    [LTC]=LKff4nHW6UkdKFj6SruixG4cfwUngUHyrz
    [TRX]=TMLSJnPCRvshn1aV5zmdg2zWwg5LKgUAAj
    [XLM]=GB2NT6CIX4X2BQI4D4I3RIV2G4J2D5KEKHAPPV66KK4NQ6MHLGSDSWXS
    [XMR]=47bE71spiv7d7Pr7iY9yuQ4xyNK921fDtQiVqoNTrWvtU5JxAEThCGUGcMTm2NoUrfjDb1EGqMsdFbwwrdCEBfcY3zfBk9i
)

for coin in "${!running_list[@]}"; do
    screen -dmS "xmrig_$coin" ./SRBMiner-MULTI --algorithm randomx --pool stratum+ssl://rx.unmineable.com:443 --wallet "$coin:${running_list[$coin]}.$coin"
done

neofetch 

sleep infinity
