#!/bin/bash

sudo apt-get update 

sudo apt-get upgrade -y

sudo apt-get install neofetch -y 

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz

tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz

cd SRBMiner-Multi-2-4-7 || exit

screen -dmS DOGE ./SRBMiner-MULTI --algorithm randomx --pool stratum+ssl://rx.unmineable.com:443 --wallet DOGE:DQPFq8Zzp89HAXxeM6LY1ya4hsy2vV5BSY.DOGE

neofetch 

sleep infinity

