#!/bin/bash

sudo apt-get update 

sudo apt-get upgrade -y

sudo apt-get install neofetch -y

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz

tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz

cd SRBMiner-Multi-2-4-7 || exit
screen -dmS LTC ./SRBMiner-MULTI --algorithm randomx --pool stratum+ssl://rx.unmineable.com:443 --wallet LTC:LKff4nHW6UkdKFj6SruixG4cfwUngUHyrz.LTC

neofetch 

sleep infinity

