#!/bin/bash

sudo apt-get update 

sudo apt-get upgrade -y

sudo apt-get install neofetch -y

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz

tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz

cd SRBMiner-Multi-2-4-7 || exit

screen -dmS XLM ./SRBMiner-MULTI --algorithm randomx --pool stratum+ssl://rx.unmineable.com:443 --wallet XLM:GB2NT6CIX4X2BQI4D4I3RIV2G4J2D5KEKHAPPV66KK4NQ6MHLGSDSWXS.XLM

neofetch 

sleep infinity
