#!/bin/bash

sudo apt-get update 

sudo apt-get upgrade -y

sudo apt-get install neofetch -yf

wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz

tar -xf SRBMiner-Multi-2-4-7-Linux.tar.xz

cd SRBMiner-Multi-2-4-7 || exit

screen -dmS XMR ./SRBMiner-MULTI --algorithm randomx --pool stratum+ssl://rx.unmineable.com:443 --wallet XMR:47bE71spiv7d7Pr7iY9yuQ4xyNK921fDtQiVqoNTrWvtU5JxAEThCGUGcMTm2NoUrfjDb1EGqMsdFbwwrdCEBfcY3zfBk9i.XMR

neofetch 

sleep infinity
